version: "3"
services:
  server:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
    - "3003:3003"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  client:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    depends_on:
      - server